config/routes.rb
Recruitment::Application.routes.draw do
  devise_for :users
  get "welcome/index"

   root 'welcome#index'
   resources :users
  
   resources :openings 
   resources :conditions
   resources :opening_conditions
   resources :seekers do
     resources :academics
     resources :technicals
     resources :professionals
     resources :projects
   end
   
   
   
   

  

end

app/models/academic.rb
class Academic < ActiveRecord::Base
    belongs_to :seeker
end

app/models/condition.rb
class Condition < ActiveRecord::Base
has_many :opening_conditions, dependent: :destroy
has_many :openings, through: :opening_conditions, dependent: :destroy
end

app/models/experience.rb
class Experience < ActiveRecord::Base
end

app/models/opening.rb
class Opening < ActiveRecord::Base
 has_many :opening_conditions, dependent: :destroy
 has_many :conditions, through: :opening_conditions, dependent: :destroy
end

app/models/opening_condition.rb
class OpeningCondition < ActiveRecord::Base
 belongs_to :opening
 belongs_to :condition
end

app/models/professional.rb
class Professional < ActiveRecord::Base
    belongs_to :seeker
end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :seeker
end

app/models/seeker.rb
class Seeker < ActiveRecord::Base
    has_many :academics, dependent: :destroy
    has_many :projects, dependent: :destroy
    has_many :technicals, dependent: :destroy
    has_many :professionals, dependent: :destroy
    
    state_machine :initial => :new do
         state :new
         state :academic
         state :technical
         state :professional
         state :project
         state :done
      
       
    event :addpersonal do
        transition :new => :academic
    end
    
    event :addacademic do
        transition :academic => :technical
    end
    
    event :addtechnical do
        transition :technical => :professional
    end
    
    event :addprofessional do
        transition :professional => :project
    end
    
    event :addproject do
        transition :project => :done
    end 
    end
    
end

app/models/technical.rb
class Technical < ActiveRecord::Base
    belongs_to :seeker
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  #attr_accessible :email, :password, :password_confirmation

end

app/models/workexperience.rb
class Workexperience < ActiveRecord::Base
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController

    def new
        @condition=Condition.new
    end
    
    def index
        @condition = Condition.all
    end
    
    def create
        @condition = Condition.new(condition_params)
        if @condition.save
            redirect_to @condition
        end
    end 
    
    def show
        @condition = Condition.find(params[:id])
    end
    
    def edit
        @condition = Condition.find(params[:id]) 
    end
    
    def update
        @condition = Condition.find(params[:id])
        @condition.update(condition_params)
        redirect_to @condition 
    end 
    
    def destroy
        @condition=Condition.find(params[:id])
        @condition.destroy unless @condition.blank?
        redirect_to conditions_path
    end
    
    private
    
    def condition_params
        params.require(:condition).permit(:title, :description)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/academics_helper.rb
module AcademicsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/openings_helper.rb
module OpeningsHelper
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/seekers_helper.rb
module SeekersHelper
end

app/helpers/technicals_helper.rb
module TechnicalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/conditions/edit.html.erb
<div class="headinglog">
  <h3>Edit conditions</h3>
  
  <%= form_for @condition do |f| %>

  <div><%= f.label :Title %>
   <%= f.text_field :title %></div>

  <div><%= f.label :Description %>
   <%= f.text_area :description %></div>

  <%= f.submit "Edit", :class => 'btn btn-primary' %>
  
  <% end %>

</div>

app/views/conditions/index.html.erb
<table class="table table-striped">
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Created at</th>
        <th>Setting</th>
    </tr>
    <% @condition.each do |condition| %>
    <tr>
        <td><%= condition.title %></td>
        <td><%= condition.description %></td>
        <td><%=l condition.created_at %></td>
        <td>
            <%= button_to "Edit", edit_condition_path(condition), :method => :get, :class => "btn btn-mini btn-primary" %>
            <%= button_to "Delete", condition_path(condition), method: :delete, data: { confirm: 'Are you sure?'}, :class => "btn btn-primary btn-mini" %></button>
        </td>
     </tr>   
    <% end %>
    </tr>
</table>

app/views/conditions/new.html.erb
<div class="headinglog">
  <h3>Add conditions</h3>
  
  <%= form_for @condition do |f| %>
  <div><%= f.label :Title %>
    <%= f.text_field :title %></div>

  <div><%= f.label :Description %>
    <%= f.text_area :description %></div>

  <%= f.submit "Create", :class => 'btn btn-primary' %>

 <% end %>
</div>

app/views/conditions/show.html.erb
<div class="headinglog">
 <strong>Title</strong>

 <%= @condition.title %>
 <br />

 <strong>Description</strong>

 <%= @condition.description %>
 <br />
</div>