config/routes.rb
Recruitment::Application.routes.draw do
  devise_for :users
  get "welcome/index"

   root 'welcome#index'
   resources :users
  
   resources :openings 
   resources :conditions
   resources :opening_conditions
   resources :seekers do
     resources :academics
     resources :technicals
     resources :professionals
     resources :projects
   end
   
   
   
   

  

end

app/models/academic.rb
class Academic < ActiveRecord::Base
    belongs_to :seeker
end

app/models/condition.rb
class Condition < ActiveRecord::Base
has_many :opening_conditions, dependent: :destroy
has_many :openings, through: :opening_conditions, dependent: :destroy
end

app/models/experience.rb
class Experience < ActiveRecord::Base
end

app/models/opening.rb
class Opening < ActiveRecord::Base
 has_many :opening_conditions, dependent: :destroy
 has_many :conditions, through: :opening_conditions, dependent: :destroy
end

app/models/opening_condition.rb
class OpeningCondition < ActiveRecord::Base
 belongs_to :opening
 belongs_to :condition
end

app/models/professional.rb
class Professional < ActiveRecord::Base
    belongs_to :seeker
end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :seeker
end

app/models/seeker.rb
class Seeker < ActiveRecord::Base
    has_many :academics, dependent: :destroy
    has_many :projects, dependent: :destroy
    has_many :technicals, dependent: :destroy
    has_many :professionals, dependent: :destroy
    
    state_machine :initial => :new do
         state :new
         state :academic
         state :technical
         state :professional
         state :project
         state :done
      
       
    event :addpersonal do
        transition :new => :academic
    end
    
    event :addacademic do
        transition :academic => :technical
    end
    
    event :addtechnical do
        transition :technical => :professional
    end
    
    event :addprofessional do
        transition :professional => :project
    end
    
    event :addproject do
        transition :project => :done
    end 
    end
    
end

app/models/technical.rb
class Technical < ActiveRecord::Base
    belongs_to :seeker
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  #attr_accessible :email, :password, :password_confirmation

end

app/models/workexperience.rb
class Workexperience < ActiveRecord::Base
end

app/controllers/seekers_controller.rb
class SeekersController < ApplicationController

  def new
    @seeker=Seeker.new
  end
  
  def index
    @opening = Opening.all
  end
 
  def create
    @seeker = Seeker.new(seeker_params)
    if @seeker.save
        @seeker.fire_state_event(:addpersonal)
        render "academics/new"
    end  
  end 
  
  private
  
  def seeker_params
    params.require(:seeker).permit(:firstname, :lastname, :email, :contact, :gender,  :birth, :localaddress, :permanentaddress, :state )
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/academics_helper.rb
module AcademicsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/openings_helper.rb
module OpeningsHelper
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/seekers_helper.rb
module SeekersHelper
end

app/helpers/technicals_helper.rb
module TechnicalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/seekers/complete.html.erb
<h1>Thanks</h1>

app/views/seekers/index.html.erb
<h1>Our openings</h1>
<div>
<% @opening.each do |open| %>

<div class="add"><p><center><%= open.title %></p>
<p><%= link_to "View more", opening_path(open.id) %></p>
</div>
<% end %>
</div>
</br />

app/views/seekers/new.html.erb
<div class="heading">
    <h2>Fill details Here</h2>
    <%= simple_form_for @seeker do |f| %>
    
      <div>
          <%= f.label :Name  %>
          <%= f.text_field :firstname, title: "Enter your First name" %>
          <%= f.text_field :lastname, title: "Enter your Lastname" %>
      </div>
      <div>
          <%= f.label :Email %>
          <%= f.email_field :email, title: "Enter your valid Email" %>
      </div>
      <div>
          <%= f.label :Contact%>
          <%= f.text_field :contact, title: "Enter contact number" %>
      </div>
      
      <div>
          <%= f.label :Gender %>
          <%= f.label(:male, "Male") %><%= f.radio_button(:gender, "male") %>
          <%= f.label(:female, "Female") %><%= f.radio_button(:gender, "female") %>
      </div>
      <div>
          <%= f.label :birth, "Date of Birth" %>
          <%= f.date_field :birth %>
      </div>
      <div>
          <%= f.label :localaddress, "Local Address" %>
          <%= f.text_area :localaddress, title: "Enter your Local Address" %>
      </div>
      <div>
          <%= f.label :permanentaddress, "Local Address" %>
          <%= f.text_area :permanentaddress, title: "Enter your Permanent Address" %>
      </div>
      <div>
          <%= f.submit "next" , :class => 'btn btn-primary' %>
      </div>
 <% end %> 
</div>    

app/views/users/complete.html.erb
<h1>Thanks</h1>

app/views/users/index.html.erb
<script>
$(document).ready(function(){
$("#job").click(function(){
$("#detail").slideDown("slow");
$("#detail2, #detail1").slideUp("slow");

});
});
$(document).ready(function(){
$("#job1").click(function(){
$("#detail1").slideDown("slow");
$("#detail, #detail2").slideUp("slow");
});
});
$(document).ready(function(){
$("#job2").click(function(){
$("#detail2").slideDown("slow");
$("#detail, #detail1").slideUp("slow");
});
});
</script>
<style>
.divi
{
  background-color:#e5eecc;
  border:solid 1px #c3c3c3;
 
}
.head
{
  padding:5px;
 
}
.dis
{
  padding:50px;
 display:none;
 
}

</style>
<div id="job" class="head divi ">job1</div>
<div id="detail" class="dis divi ">description</div>

<div id="job1" class="head divi ">job2</div>
<div id="detail1" class="dis divi ">Description</div>

<div id="job2" class="head divi ">job3</div>
<div id="detail2" class="dis divi">Description</div>

<center><button><%= link_to "I agreed proceed" , new_user_path %></button></center>

app/views/users/new.html.erb
<script
src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
</script>
<script>
$(document).ready(function(){
$("#f1").click(function(){
$("#t1").slideDown("slow");
});
});
$(document).ready(function(){
$("#f2").click(function(){
$("#t2").slideDown("slow");
});
});
$(document).ready(function(){
$("#f3").click(function(){
$("#t3").slideDown("slow");
});
});
</script>
<style>
.hide
{
  display:none;
}
fieldset 
{
  border-radius: 10px;
    border: 5px solid #009;
  padding: 1em;
  font:80%/1 sans-serif;
}
legend
{
    
  
  font-size:20px;
  border-top: 2px solid #009;
  border-left: 2px solid #009;
  border-right:  2px solid #009;
  border-radius: 10px;
}
</style>
<h1>Fill details Here</h1>
<div>
   <%= form_for @user do |f| %>
   <fieldset id="f1" >
    <legend>Personal-Details</legend>
    
    <table id="t1" class="hide">
      <tr>
        <th>Name</th>
         <td><%= f.text_field :firstname %></td>
         <td><%= f.text_field :lastname %></td>
      </tr>
      <tr>
          <th>Email</th>
          <td><%= f.email_field :email %></td>
      </tr>
      <tr>          
          <th>Contact</th>
          <td><%= f.text_field :contact %><td>
      </tr>
      <tr>
        <th>Local address</th>
        <td><%= text_area_tag :localaddress %></td>
        <th>Permanent address</th>
        <td><%= text_area_tag :permanentaddress %></td>
      </tr>  
    </table>
 
  </fieldset>
  <br />
  <fieldset id="f2">
   <legend>Academic-Details</legend>
   <%= f.fields_for :academics do |s| %>
    <table id="t2" class="hide">
      <tr>
        <th>Course</th>
        <td><%= s.text_field :course %></td>
      </tr>
      <tr>
        <th>Passing Year</th>
        <td><%= s.text_field :pass_year %></td>
      </tr>
      <tr>
        <th>Board/University</th>
        <td><%= s.text_field :board %></td>
      </tr>
      <tr>
        <th>Percentage</th>
        <td><%= s.text_field :percentage %></td>
      </tr>
      <tr>
        <th>Place</th>
        <td><%= s.text_field :place %></td>
      </tr>
      <tr>
        <th>Institute</th>
        <td><%= s.text_field :institute %></td>
      </tr>
    </table>
    <% end %>
  </fieldset>
  <br />
  <fieldset id="f3">
  <legend>Technical-Detail</legend>
  <%= f.fields_for :technicals do |t| %>
   <table id="t3" class="hide">
    <tr>
     <th>Programming Skills</th>
     <td><%= t.text_field :programming_skills %>
    </tr>
     <tr>
     <th>WEB Technologies</th>
     <td><%= t.text_field :web_skills %>
    </tr>
     <tr>
     <th>Databases Known</th>
     <td><%= t.text_field :database %>
    </tr>
     <tr>
     <th>Others</th>
     <td><%= t.text_field :others %>
    </tr>
   </table>
  <% end %>
  <%= f.submit "Save" %>
  <% end %> 
</div>      

app/views/users/show.html.erb
<h1 class="headinglog">Welcome to your dashboard</h1>