config/routes.rb
Recruitment::Application.routes.draw do
  devise_for :users
  get "welcome/index"

   root 'welcome#index'
   resources :users
  
   resources :openings 
   resources :conditions
   resources :opening_conditions
   resources :seekers do
     resources :academics
     resources :technicals
     resources :professionals
     resources :projects
   end
   
   
   
   

  

end

app/models/academic.rb
class Academic < ActiveRecord::Base
    belongs_to :seeker
end

app/models/condition.rb
class Condition < ActiveRecord::Base
has_many :opening_conditions, dependent: :destroy
has_many :openings, through: :opening_conditions, dependent: :destroy
end

app/models/experience.rb
class Experience < ActiveRecord::Base
end

app/models/opening.rb
class Opening < ActiveRecord::Base
 has_many :opening_conditions, dependent: :destroy
 has_many :conditions, through: :opening_conditions, dependent: :destroy
end

app/models/opening_condition.rb
class OpeningCondition < ActiveRecord::Base
 belongs_to :opening
 belongs_to :condition
end

app/models/professional.rb
class Professional < ActiveRecord::Base
    belongs_to :seeker
end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :seeker
end

app/models/seeker.rb
class Seeker < ActiveRecord::Base
    has_many :academics, dependent: :destroy
    has_many :projects, dependent: :destroy
    has_many :technicals, dependent: :destroy
    has_many :professionals, dependent: :destroy
    
    state_machine :initial => :new do
         state :new
         state :academic
         state :technical
         state :professional
         state :project
         state :done
      
       
    event :addpersonal do
        transition :new => :academic
    end
    
    event :addacademic do
        transition :academic => :technical
    end
    
    event :addtechnical do
        transition :technical => :professional
    end
    
    event :addprofessional do
        transition :professional => :project
    end
    
    event :addproject do
        transition :project => :done
    end 
    end
    
end

app/models/technical.rb
class Technical < ActiveRecord::Base
    belongs_to :seeker
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  #attr_accessible :email, :password, :password_confirmation

end

app/models/workexperience.rb
class Workexperience < ActiveRecord::Base
end

app/controllers/openings_controller.rb
class OpeningsController < ApplicationController
    def new
        @opening = Opening.new
    end
  
  
    def index
        @opening = Opening.all
    end
  
  
    def create
        @opening = Opening.new(opening_params)
        if @opening.save
          conditions = params[:opening][:condition_ids]
          conditions.each do |condition_id|
              @condition = @opening.opening_conditions.create!(:condition_id => condition_id) unless condition_id.blank?
          end
        redirect_to @opening
        end
    end 
  
  
    def show
        @opening = Opening.find(params[:id])
        @conditions = @opening.opening_conditions
    end
    
    
    def edit
        @opening = Opening.find(params[:id]) 
        @condition = @opening.opening_conditions
    end
  
  
    def update
        @opening = Opening.find(params[:id])
        @opening.opening_conditions.destroy_all
        if @opening.update(opening_params)
            conditions = params[:opening][:condition_ids]
            conditions.each do |condition_id|
                @opening.opening_conditions.create!(:condition_id => condition_id) unless condition_id.blank?
            end
        end 
        redirect_to @opening 
    end 
  
  
    def destroy
        @opening=Opening.find(params[:id])
        @opening.destroy unless @opening.blank?
        redirect_to openings_path
    end
  
    private
    
    def opening_params
        params.require(:opening).permit(:title, :jtype, :description)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/academics_helper.rb
module AcademicsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/openings_helper.rb
module OpeningsHelper
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/seekers_helper.rb
module SeekersHelper
end

app/helpers/technicals_helper.rb
module TechnicalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/openings/edit.html.erb
<div class="headinglog">
<h1>Editing Job</h1>
 
<%= simple_form_for @opening, url: opening_path(@opening), method: :patch do |f| %>
 
  <div><%= f.label :Title %>
  <%= f.text_field :title %></div>

  <div><%= f.label :Type %>
  <%= f.select(:jtype, options_for_select([['Fresher', 'Fresher'], ['Experience', 'Experience']])) %>

  <div><%= f.label :Description %>
  <%= f.text_area :description %></div>
  
  <%= f.association :conditions, as: :check_boxes %>
  
  <%= f.submit "Update", :class => 'btn btn-primary' %>

</div>
<% end %>
</div>

app/views/openings/index.html.erb
<table  class="table table-striped">
    <tr>
       
        <th>Title</th>
        <th>Type</th>
        <th>Detail</th>
        <th>Created At</th>
        <th>Settings</th>
    </tr>   
    <% @opening.each do |opening| %>
    <tr>
       
        <td><%= opening.title %></td>
        <td><%= opening.jtype %></td>
        <td><%= opening.description %></td>
        <td><%=l opening.created_at %></td>
        <td>
            <%= button_to "Edit", edit_opening_path(opening), :method => :get, :class => 'btn btn-mini btn-primary' %>
            <%= button_to "Delete", opening_path(opening), method: :delete, data: { confirm: 'Are you sure?'} , :class => "btn-mini  btn-primary"%>
        </td>
    </tr>
    <% end %>
</table>

app/views/openings/new.html.erb
<div class="headinglog">
<h3>Make  the current opening here</h3>

<%= simple_form_for @opening do |f| %>
 
 <div>
  <%= f.label :Title %>
  <%= f.text_field :title %>
 </div>

 <div>
  <%= f.label :Type %>
  <%= f.select(:jtype, options_for_select([['Fresher', 'Fresher'], ['Experience', 'Experience']])) %>
 </div>

 <div>
  <%= f.label :Description %>
  <%= f.text_area :description %>
 </div>
 
 <%= f.association :conditions, as: :check_boxes %>
 
 <%= f.submit "Create", :class => 'btn btn-primary' %>

<% end %>
</div>

app/views/openings/show.html.erb
<style>
fieldset
{
    width:300px;
    
    border-style:groove;
    color:green;
}
legend
{
    color:red;
    font_size:30px;
}
.divi
{
   background-color:yellow;
   width:100px;
   margin-top:100px;
    float:left;
}
.p1
{
    font-size:15px;
}
</style>
<center>
    <div class="heading">
        <h3>About Opening</h3>
        <fieldset>
            <legend>Title</legend>
 
            <p class="p1"><%= @opening.title %></p>

        </fieldset>
        <br />
        <fieldset>
            <legend>Type</legend>
        
            <p class="p1"><%= @opening.jtype %></p>

        </fieldset>
        <br />
        <fieldset>
            <legend>Description:</legend>
        
            <p class="p1"><%= @opening.description %></p>

        </fieldset>
        <br />
        <fieldset>
            <legend>Terms & Conditions</legend>
        
            <% @conditions.each do |cond| %>
                <p class="p1"><%= cond.condition.description %></p>
            <% end %>
        </fieldset>
        <br />
        <% if !user_signed_in? %>
            <%= link_to "Apply Here | ", new_seeker_path %>
        <% end %>
        <%= link_to "Back", :back %>
</center>