config/routes.rb
Recruitment::Application.routes.draw do
  devise_for :users
  get "welcome/index"

   root 'welcome#index'
   resources :users
  
   resources :openings 
   resources :conditions
   resources :opening_conditions
   resources :seekers do
     resources :academics
     resources :technicals
     resources :professionals
     resources :projects
   end
   
   
   
   

  

end

app/models/academic.rb
class Academic < ActiveRecord::Base
    belongs_to :seeker
end

app/models/condition.rb
class Condition < ActiveRecord::Base
has_many :opening_conditions, dependent: :destroy
has_many :openings, through: :opening_conditions, dependent: :destroy
end

app/models/experience.rb
class Experience < ActiveRecord::Base
end

app/models/opening.rb
class Opening < ActiveRecord::Base
 has_many :opening_conditions, dependent: :destroy
 has_many :conditions, through: :opening_conditions, dependent: :destroy
end

app/models/opening_condition.rb
class OpeningCondition < ActiveRecord::Base
 belongs_to :opening
 belongs_to :condition
end

app/models/professional.rb
class Professional < ActiveRecord::Base
    belongs_to :seeker
end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :seeker
end

app/models/seeker.rb
class Seeker < ActiveRecord::Base
    has_many :academics, dependent: :destroy
    has_many :projects, dependent: :destroy
    has_many :technicals, dependent: :destroy
    has_many :professionals, dependent: :destroy
    
    state_machine :initial => :new do
         state :new
         state :academic
         state :technical
         state :professional
         state :project
         state :done
      
       
    event :addpersonal do
        transition :new => :academic
    end
    
    event :addacademic do
        transition :academic => :technical
    end
    
    event :addtechnical do
        transition :technical => :professional
    end
    
    event :addprofessional do
        transition :professional => :project
    end
    
    event :addproject do
        transition :project => :done
    end 
    end
    
end

app/models/technical.rb
class Technical < ActiveRecord::Base
    belongs_to :seeker
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  #attr_accessible :email, :password, :password_confirmation

end

app/models/workexperience.rb
class Workexperience < ActiveRecord::Base
end

app/helpers/academics_helper.rb
module AcademicsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/openings_helper.rb
module OpeningsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/seekers_helper.rb
module SeekersHelper
end

app/helpers/technicals_helper.rb
module TechnicalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Recruitment" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
  <!--- Header start -->
    <header>
          <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="logo"><a href="http://localhost:3000/"><%= image_tag "small-logo.png" %></a></div>
                    </div>
                    <div class="col-lg-3 pull-right header_login">
                        <div class="row">
                            <div class="col-lg-6">
                                <% if !user_signed_in? %>
                                    <button class="btn btn-lg btn-success col-lg-12 pull-left" type="button"><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></button>
                                <% end %> 
                                <% if user_signed_in? %>
                                    <button class="btn btn-lg btn-success col-lg-12 pull-right" type="button"><li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li></button>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    <p class="navbar-text pull-right">
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
         <% if user_signed_in? %>
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
             
              Welcome <strong><%= current_user.email %></strong>.
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
              
              <li><%= link_to "Add New Opening", new_opening_path %></li>
              <li><%= link_to "See All Openings", openings_path %></li>
              <li><%= link_to "Add Terms & Conditions", new_condition_path %>
              <li><%= link_to "See All Conditions", conditions_path %></li>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->
    <!--- footer start -->
      <footer>
         <p>&copy; Company 2013</p>
         
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
      </footer>
  </body>
</html> 